const nav=document.getElementById('nav');
const glow=document.querySelector('.cursor-glow');
const words=['Relax zone.','Sofa mood.','Coffee time.','Quiet living.'];
let i=0;
setInterval(()=>{i=(i+1)%words.length;document.getElementById('word').textContent=words[i]},1500);
window.addEventListener('scroll',()=>{nav.classList.toggle('scrolled',scrollY>30);document.querySelectorAll('.parallax').forEach(el=>{el.style.translate=`0 ${scrollY*-0.04}px`})});
window.addEventListener('mousemove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.15});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
document.querySelectorAll('.thumb').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.thumb').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const img=document.getElementById('mainProduct');img.style.opacity=.2;setTimeout(()=>{img.src=btn.dataset.img;img.style.opacity=1},180)}));
const modal=document.getElementById('modal');
document.querySelectorAll('.lightbox').forEach(img=>img.addEventListener('click',()=>{modal.querySelector('img').src=img.src;modal.classList.add('open')}));
modal.addEventListener('click',()=>modal.classList.remove('open'));
