export const locales = {
  en: {
    meta: { title: 'Juzur | SofaTray for Modern Homes', description: 'Juzur creates premium wooden SofaTray pieces for coffee, phones, remotes, snacks and relaxed sofa moments in modern homes.' },
    nav: { label: 'Primary navigation', product: 'Product', video: 'Video', wood: 'Zan Wood', gift: 'Gift', faq: 'FAQ', order: 'Order Now', menuOpen: 'Open menu', menuClose: 'Close menu', switchLanguage: 'Switch to Arabic' },
    hero: { label: 'SofaTray by Juzur hero', eyebrow: 'Premium Wooden Sofa Tray', title1: 'Everything you need.', title2: 'Right beside you.', support: 'Designed to make life easier.', text: 'Coffee. Phone. Remote. Beautifully organized.', view: 'View Product', special: 'Launch price', priceLabel: 'Launch price: EGP 1,999, previously EGP 2,499', trustLabel: 'Product trust signals', wood: 'Handcrafted Zan Wood', payment: 'Cash on Delivery', delivery: 'Delivery within 4–7 days', scroll: 'Scroll', mediaLabel: 'Choose hero product media', videoPlay: 'Play SofaTray hero video', videoAlt: 'SofaTray by Juzur in use' },
    images: { studio: 'SofaTray studio product view', side: 'SofaTray handcrafted side view', lifestyle: 'SofaTray arranged for a cozy sofa moment', top: 'SofaTray top view', details: 'SofaTray product details on a clean studio background', cozy: 'SofaTray with coffee, phone and remote in a cozy living room', boxOpen: 'Open Juzur gift box with the SofaTray inside', sofa: 'SofaTray opened across a sofa arm', boxClosed: 'Closed eco-friendly Juzur product box', packaging: 'Juzur product packaging in a natural living space', enlarge: 'Enlarge', preview: 'SofaTray image preview' },
    video: { eyebrow: 'Video', title: 'See SofaTray in action.', text: 'Watch how SofaTray by Juzur keeps your coffee, phone, remote and snacks beside you beautifully, neatly and within easy reach.', demoLabel: 'SofaTray product demonstration', unsupported: 'Your browser does not support embedded video.', play: 'Play', soonLabel: 'video coming soon', soon: 'video will be added soon.', items: [['Coffee setup', 'Short demo video'], ['Daily essentials', 'Phone, remote, snacks, and cup']] },
    gift: { eyebrow: 'Gift idea', title: 'A practical gift that feels personal.', text: 'SofaTray by Juzur is easy to understand the moment it is opened: a warm wooden piece for coffee, phone, remote and relaxed sofa time. It works beautifully for new homes, birthdays, Ramadan gatherings and thoughtful everyday gifting.', reasons: 'Gift reasons', points: ['Useful every day', 'Premium wooden feel', 'Ready for home moments'], cta: 'Order as a Gift', photos: 'Gift presentation photos', ready: 'Gift ready', presented: 'Presented with care', caption: 'Branded packaging makes the first impression feel as thoughtful as the product inside.', boxAlt: 'SofaTray in its branded Juzur gift box' },
    material: { eyebrow: 'Why Zan wood', title: 'Natural strength with a warm furniture finish.', text: 'Made from Zan wood, SofaTray brings a naturally rich feel to everyday living-room routines while keeping the warm look of real furniture.' },
    product: { eyebrow: 'Product features', title: 'Daily essentials, beautifully organized.', text: 'A smart wooden sofa tray designed to keep your coffee, phone, remote, snacks and small daily essentials beside you neatly and within easy reach.', features: ['Sliding / folding tray design', 'Cup holder, phone slot and essentials area', 'Premium Zan wood feel with rounded edges'], dimensions: 'Product dimensions' },
    gallery: { eyebrow: 'Gallery', title: 'Handmade details with a premium natural feel.' },
    faq: { eyebrow: 'FAQ', title: 'Quick answers before you order.', items: [['How long does delivery take?', 'Delivery usually takes 4–7 days after we confirm your order details.'], ['What wood is used?', 'SofaTray is made from Zan wood for a warm, premium furniture feel.'], ['What can it hold?', 'It is made for coffee, phones, remotes, snacks, and small daily essentials beside the sofa.'], ['How do I pay?', 'Payment is Cash on Delivery when your order is delivered.'], ['How is the delivery fee calculated?', 'It is confirmed by phone based on the governorate before delivery.']] },
    checkout: { eyebrow: 'Cash on Delivery', title: 'Complete your order.', delivery: 'Delivery within 4–7 days', offerLabel: 'Launch price: EGP 1,999, previously EGP 2,499', price: 'Launch price', intro: 'Enter your details and we will call you to confirm delivery and the final delivery fee.', labels: { fullName: 'Full name', phone: 'Mobile number', governorate: 'Governorate', areaCity: 'Area / city', detailedAddress: 'Detailed delivery address', landmark: 'Landmark (optional)', quantity: 'Number of pieces' }, select: 'Select governorate', submit: 'Confirm Cash on Delivery Order', sending: 'Sending order...', errors: { fullName: 'Enter your full name.', phoneEmpty: 'Enter your mobile number.', phoneInvalid: 'Enter a valid Egyptian mobile number beginning with 010, 011, 012, or 015.', governorate: 'Select your governorate.', areaCity: 'Enter your area or city.', detailedAddress: 'Enter the detailed delivery address.', quantity: 'Enter a quantity of 1 or more.', summary: 'Please correct the highlighted fields and try again.' }, statuses: { sending: 'Sending your order request...', success: 'Your order request has been sent. We will call you to confirm the delivery details and final delivery fee.', failure: 'We could not send your order. Please check your connection and try again.' } },
    modal: { label: 'Product image preview', close: 'Close image preview' },
    footer: { tagline: 'Rooted in natural living. Crafted by Techwood-Art.', contact: 'Contact: 01095306518', call: 'Call Juzur at 01095306518' },
    governorates: ['Alexandria','Aswan','Asyut','Beheira','Beni Suef','Cairo','Dakahlia','Damietta','Faiyum','Gharbia','Giza','Ismailia','Kafr El Sheikh','Luxor','Matrouh','Minya','Monufia','New Valley','North Sinai','Port Said','Qalyubia','Qena','Red Sea','Sharqia','Sohag','South Sinai','Suez'],
  },
  ar: {
    meta: { title: 'Juzur | ترابيزة الكنبة الخشبية', description: 'ترابيزة خشبية لذراع الكنبة من Juzur، مصنوعة بعناية علشان تخلي قهوتك وموبايلك والريموت دايمًا جنبك.' },
    nav: { label: 'التنقل الرئيسي', product: 'المميزات', video: 'شوفها وهي بتُستخدم', wood: 'خشب الزان', gift: 'هدية مميزة', faq: 'الأسئلة الشائعة', order: 'اطلبها دلوقتي', menuOpen: 'افتح القائمة', menuClose: 'أغلق القائمة', switchLanguage: 'التبديل إلى الإنجليزية' },
    hero: { label: 'ترابيزة الكنبة من Juzur', eyebrow: 'ترابيزة خشبية لذراع الكنبة، بتصميم عملي وأنيق', title1: 'كل حاجة بتحبها...', title2: 'جنبك', support: 'راحة أكتر في كل لحظة', text: 'قهوتك، موبايلك، والريموت... كل حاجة مرتبة وفي متناول إيدك.', view: 'شوفها وهي بتُستخدم', special: 'السعر بعد الخصم', priceLabel: 'السعر بعد الخصم 2,000 جنيه، بدلًا من 2,500 جنيه. وفّر 500 جنيه.', trustLabel: 'مميزات الشراء', wood: 'مصنوعة يدويًا من خشب الزان', payment: 'الدفع عند الاستلام', delivery: 'التوصيل خلال ٤–٧ أيام', scroll: 'اكتشف التفاصيل', mediaLabel: 'اختر صورة أو فيديو للمنتج', videoPlay: 'شغّل فيديو ترابيزة الكنبة', videoAlt: 'ترابيزة الكنبة من Juzur أثناء الاستخدام' },
    images: { studio: 'ترابيزة الكنبة من Juzur في الاستوديو', side: 'تفاصيل ترابيزة الكنبة المصنوعة يدويًا من الجانب', lifestyle: 'ترابيزة الكنبة مجهزة للحظات الراحة', top: 'ترابيزة الكنبة من الأعلى', details: 'تفاصيل ترابيزة الكنبة على خلفية بسيطة', cozy: 'ترابيزة الكنبة مع القهوة والموبايل والريموت في غرفة المعيشة', boxOpen: 'علبة هدايا Juzur مفتوحة وبداخلها ترابيزة الكنبة', sofa: 'ترابيزة Juzur على ذراع الكنبة', boxClosed: 'علبة Juzur مغلقة', packaging: 'تغليف Juzur في أجواء منزلية طبيعية', enlarge: 'كبّر الصورة', preview: 'معاينة صورة ترابيزة الكنبة' },
    video: { eyebrow: 'شوفها وهي بتُستخدم', title: 'راحة أكتر... وكل حاجة في مكانها', text: 'شوف إزاي ترابيزة الكنبة من Juzur بتخلّي كل حاجتك مرتبة وجنبك، من غير زحمة ومن غير ما تقوم كل شوية.', demoLabel: 'فيديو توضيحي لترابيزة الكنبة', unsupported: 'للأسف، متصفحك مش بيدعم تشغيل الفيديو.', play: 'شغّل الفيديو', soonLabel: 'قريبًا', soon: 'هنضيف الفيديو قريبًا.', items: [] },
    gift: { eyebrow: 'هدية عملية ومميزة', title: 'هدية أنيقة هتُستخدم كل يوم', text: 'مش بس شكلها أنيق؛ دي هدية عملية بتضيف راحة ولمسة دافية لكل لحظة في البيت.', reasons: 'مميزات الهدية', points: ['عملية للاستخدام اليومي', 'خشب طبيعي بلمسة فاخرة', 'تغليف أنيق وجاهز للإهداء'], cta: 'اطلبها هدية', photos: 'صور تقديم الهدية', ready: 'جاهزة للإهداء', presented: 'عناية في كل تفصيلة', caption: 'تغليف Juzur الأنيق بيخلّي الهدية مميزة من أول لحظة.', boxAlt: 'ترابيزة الكنبة داخل علبة هدايا Juzur' },
    material: { eyebrow: 'ليه اخترنا خشب الزان؟', title: 'متانة طبيعية وشكل يليق ببيتك', text: 'اخترنا خشب الزان لقوته وشكله الطبيعي الجميل، علشان ترابيزة الكنبة تعيش معاك وتضيف لمسة دافية وأنيقة لبيتك.' },
    product: { eyebrow: 'عملية في كل تفصيلة', title: 'كل احتياجاتك مرتبة وفي متناول إيدك', text: 'تصميم مرن بيتحط بسهولة على ذراع الكنبة، وبيجمع حاجتك اليومية في مكان واحد، علشان تستمتع بوقت راحتك من غير زحمة.', features: ['تصميم مرن وسهل الطي', 'مكان للكوب وحامل للموبايل', 'مساحة للريموت، والتسالي، والحاجات الصغيرة', 'خشب زان طبيعي، بحواف ناعمة وتشطيب يدوي'], dimensions: 'أبعاد المنتج' },
    gallery: { eyebrow: 'اكتشف التفاصيل', title: 'صناعة يدوية بعناية في كل تفصيلة' },
    faq: { eyebrow: 'قبل ما تطلب', title: 'إجابات واضحة على أهم أسئلتك', items: [['التوصيل بياخد قد إيه؟', 'التوصيل بيتم عادةً خلال ٤–٧ أيام من وقت تسجيل الطلب.'], ['ترابيزة الكنبة مصنوعة من إيه؟', 'مصنوعة يدويًا من خشب الزان الطبيعي، بتشطيب ناعم وشكل أنيق يليق ببيتك.'], ['ممكن أحط عليها إيه؟', 'تقدر ترتّب عليها الكوب، والموبايل، والريموت، والتسالي، والحاجات الصغيرة اللي بتحب تفضل جنبك.'], ['الدفع بيكون إزاي؟', 'الدفع عند الاستلام.'], ['تكلفة التوصيل بتتحسب إزاي؟', 'تكلفة التوصيل بتتحسب حسب المحافظة، من غير مكالمة لتأكيد الطلب.']] },
    checkout: { eyebrow: 'الدفع عند الاستلام', title: 'كمّل طلبك في خطوات بسيطة', delivery: 'التوصيل خلال ٤–٧ أيام', offerLabel: 'السعر بعد الخصم 2,000 جنيه، بدلًا من 2,500 جنيه. وفّر 500 جنيه.', price: 'السعر بعد الخصم', intro: 'اكتب بياناتك واضغط «تأكيد الطلب» لإرسال طلبك. الدفع عند الاستلام.', labels: { fullName: 'الاسم بالكامل', phone: 'رقم الموبايل', governorate: 'المحافظة', areaCity: 'المنطقة أو المدينة', detailedAddress: 'عنوان التوصيل بالتفصيل', landmark: 'علامة مميزة قريبة (اختيارية)', quantity: 'عدد القطع' }, select: 'اختار محافظتك', submit: 'تأكيد الطلب والدفع عند الاستلام', sending: 'جاري إرسال طلبك...', errors: { fullName: 'من فضلك اكتب اسمك بالكامل.', phoneEmpty: 'من فضلك اكتب رقم الموبايل.', phoneInvalid: 'اكتب رقم موبايل مصري صحيح يبدأ بـ 010 أو 011 أو 012 أو 015.', governorate: 'اختار محافظتك.', areaCity: 'اكتب المنطقة أو المدينة.', detailedAddress: 'اكتب عنوان التوصيل بالتفصيل.', quantity: 'اختار قطعة واحدة أو أكثر.', summary: 'راجع الخانات الموضحة، وبعدها حاول مرة تانية.' }, statuses: { sending: 'جاري إرسال طلبك...', success: 'تم إرسال طلبك بنجاح. شكرًا لاختيارك Juzur.', failure: 'للأسف، ماقدرناش نرسل طلبك. اتأكد من اتصالك بالإنترنت وحاول مرة تانية.' } },
    modal: { label: 'معاينة صورة المنتج', close: 'أغلق معاينة الصورة' },
    footer: { tagline: 'منتجات خشبية مصنوعة بعناية، علشان تضيف راحة وأناقة لتفاصيل يومك. تنفيذ Techwood-Art.', contact: 'للطلب والاستفسار: 01095306518', call: 'اتصل بـ Juzur على 01095306518' },
    governorates: ['الإسكندرية','أسوان','أسيوط','البحيرة','بني سويف','القاهرة','الدقهلية','دمياط','الفيوم','الغربية','الجيزة','الإسماعيلية','كفر الشيخ','الأقصر','مطروح','المنيا','المنوفية','الوادي الجديد','شمال سيناء','بورسعيد','القليوبية','قنا','البحر الأحمر','الشرقية','سوهاج','جنوب سيناء','السويس'],
  },
};

// Current premium offer copy.
locales.en.hero.special = 'Current price';
locales.en.hero.priceLabel = 'Current price EGP 2,000, previously EGP 2,500. Save EGP 500.';
locales.en.checkout.price = 'Current price';
locales.en.checkout.offerLabel = 'Current price EGP 2,000, previously EGP 2,500. Save EGP 500.';

function replaceProductName(value, replacements) {
  if (typeof value === 'string') return replacements.reduce((copy, [from, to]) => copy.replaceAll(from, to), value);
  if (Array.isArray(value)) return value.map((item) => replaceProductName(item, replacements));
  if (value && typeof value === 'object') Object.keys(value).forEach((key) => { value[key] = replaceProductName(value[key], replacements); });
  return value;
}

replaceProductName(locales.en, [['SofaTray by Juzur', 'Juzur Sofa tray'], ['SofaTray', 'Juzur Sofa tray'], ['Sofa Tray', 'Juzur Sofa tray']]);
locales.en.checkout.intro = 'Enter your details and confirm your order. It will be registered automatically.';
locales.en.checkout.statuses.success = 'Your order has been registered successfully. No confirmation call is required.';
locales.en.faq.items[0][1] = 'Delivery usually takes 4–7 days from the time your order is registered.';
locales.en.faq.items[4][1] = 'The delivery fee is calculated by governorate without a confirmation call.';

function replaceVisibleBrand(value, key = '') {
  if (key === 'meta') return value;
  if (typeof value === 'string') return value.replaceAll('JUZUR', 'چذور').replaceAll('Juzur', 'چذور');
  if (Array.isArray(value)) return value.map((item) => replaceVisibleBrand(item));
  if (value && typeof value === 'object') Object.keys(value).forEach((childKey) => { value[childKey] = replaceVisibleBrand(value[childKey], childKey); });
  return value;
}

replaceVisibleBrand(locales.en);
replaceVisibleBrand(locales.ar);
