import { useRef, useState } from 'react';
import { calculateOrderTotals, formatPrice, product } from '../config/product.js';
import { createOrderHelpUrl, createOrderPayload, createOrderSuccessMessage, createSubmissionGate, isValidEgyptianMobile, submitOrder } from '../utils/order.js';
import { createMetaPurchaseParameters, trackMetaEvent } from '../utils/metaPixel.js';
import { useLanguage } from '../i18n/LanguageContext.jsx';
const governorateValues = ['Alexandria','Aswan','Asyut','Beheira','Beni Suef','Cairo','Dakahlia','Damietta','Faiyum','Gharbia','Giza','Ismailia','Kafr El Sheikh','Luxor','Matrouh','Minya','Monufia','New Valley','North Sinai','Port Said','Qalyubia','Qena','Red Sea','Sharqia','Sohag','South Sinai','Suez'];
const initialForm = { fullName:'', phone:'', governorate:'', areaCity:'', detailedAddress:'', landmark:'', quantity:'1' };
function fieldError(name, value) { const valueText = String(value).trim(); if (name === 'fullName' && !valueText) return 'fullName'; if (name === 'phone') { if (!valueText) return 'phoneEmpty'; if (!isValidEgyptianMobile(valueText)) return 'phoneInvalid'; } if (name === 'governorate' && !valueText) return 'governorate'; if (name === 'areaCity' && !valueText) return 'areaCity'; if (name === 'detailedAddress' && !valueText) return 'detailedAddress'; if (name === 'quantity' && (!Number.isInteger(Number(value)) || Number(value) < 1)) return 'quantity'; return ''; }
function FormField({ id, label, error, children, className='' }) { return <div className={`form-field ${className}`.trim()}><label htmlFor={id}>{label}</label>{children}{error && <p className="field-error" id={`${id}-error`}>{error}</p>}</div>; }
export default function CheckoutSection() {
  const { language, t } = useLanguage(); const [form,setForm] = useState(initialForm); const [errors,setErrors] = useState({}); const [status,setStatus] = useState({key:'',type:''}); const [helpPayload,setHelpPayload] = useState(null); const [isSubmitting,setIsSubmitting] = useState(false); const submittingRef = useRef(createSubmissionGate()); const quantity = Math.max(1,Number(form.quantity)||1); const { subtotal, shippingFee, total } = calculateOrderTotals({ quantity, governorate: form.governorate });
  const helpUrl = helpPayload ? createOrderHelpUrl(helpPayload, language) : '';
  const statusMessage = status.key === 'summary' ? t.checkout.errors.summary : status.key === 'success' ? createOrderSuccessMessage({successMessage:t.checkout.statuses.success,language,orderId:status.orderId}) : status.key ? t.checkout.statuses[status.key] : '';
  const updateField = ({target:{name,value}}) => { setForm((current)=>({...current,[name]:value})); if(errors[name]) setErrors((current)=>({...current,[name]:fieldError(name,value)})); };
  const validateField = ({target:{name,value}}) => setErrors((current)=>({...current,[name]:fieldError(name,value)}));
  const fieldProps = (name) => ({id:name,name,value:form[name],onChange:updateField,onBlur:validateField,'aria-invalid':Boolean(errors[name]),'aria-describedby':errors[name]?`${name}-error`:undefined});
  async function handleSubmit(event) { event.preventDefault(); if(helpUrl)return; const nextErrors=Object.fromEntries(Object.entries(form).filter(([name])=>name!=='landmark').map(([name,value])=>[name,fieldError(name,value)]).filter(([,error])=>error)); if(Object.keys(nextErrors).length){setErrors(nextErrors);setStatus({key:'summary',type:'error'});document.getElementById(Object.keys(nextErrors)[0])?.focus();return;} if(!submittingRef.current.tryStart())return;setIsSubmitting(true);setStatus({key:'sending',type:''}); const payload=createOrderPayload({form,language,quantity,product}); try {const result=await submitOrder(payload);trackMetaEvent('Purchase',createMetaPurchaseParameters({orderId:result.orderId,product,quantity,subtotal:payload.subtotal}),{eventID:payload.orderId});setForm(initialForm);setErrors({});setStatus({key:'success',orderId:result.orderId,type:'success'});} catch {setHelpPayload(payload);setStatus({key:'uncertain',type:'error'});} finally{submittingRef.current.finish();setIsSubmitting(false);} }
  return <section className="checkout-section" id="checkout"><div className="checkout-copy reveal"><p className="eyebrow dark">{t.checkout.eyebrow}</p><h2>{t.checkout.title}</h2><p className="checkout-reassurance">{t.checkout.delivery}</p><div className="checkout-price-panel launch-price" aria-label={t.checkout.offerLabel}><div className="price-main"><span>{t.checkout.price}</span><span className="price-comparison"><del><bdi>{formatPrice(product.listUnitPrice,language)}</bdi></del><strong><bdi>{formatPrice(product.finalUnitPrice,language)}</bdi></strong><span className="checkout-discount-badge">{language === 'ar' ? 'وفّر 500 جنيه' : 'Save EGP 500'}</span></span></div></div><p>{t.checkout.intro}</p></div><form className="checkout-form reveal delay" id="checkoutForm" onSubmit={handleSubmit} noValidate><div className="checkout-fields">
    <FormField id="fullName" label={t.checkout.labels.fullName} error={t.checkout.errors[errors.fullName]}><input {...fieldProps('fullName')} type="text" autoComplete="name" required /></FormField>
    <FormField id="phone" label={t.checkout.labels.phone} error={t.checkout.errors[errors.phone]}><input {...fieldProps('phone')} type="tel" autoComplete="tel" inputMode="tel" placeholder="010 1234 5678" dir="ltr" required /></FormField>
    <FormField id="governorate" label={t.checkout.labels.governorate} error={t.checkout.errors[errors.governorate]}><select {...fieldProps('governorate')} autoComplete="address-level1" required><option value="" disabled>{t.checkout.select}</option>{governorateValues.map((value,index)=><option value={value} key={value}>{t.governorates[index]}</option>)}</select></FormField>
    <FormField id="areaCity" label={t.checkout.labels.areaCity} error={t.checkout.errors[errors.areaCity]}><input {...fieldProps('areaCity')} type="text" autoComplete="address-level2" required /></FormField>
    <FormField id="detailedAddress" label={t.checkout.labels.detailedAddress} error={t.checkout.errors[errors.detailedAddress]} className="full-width"><textarea {...fieldProps('detailedAddress')} rows="3" autoComplete="street-address" required /></FormField>
    <FormField id="landmark" label={t.checkout.labels.landmark} error={t.checkout.errors[errors.landmark]} className="full-width"><input {...fieldProps('landmark')} type="text" autoComplete="address-line2" /></FormField>
    <FormField id="quantity" label={t.checkout.labels.quantity} error={t.checkout.errors[errors.quantity]}><input {...fieldProps('quantity')} type="number" min="1" step="1" inputMode="numeric" required /></FormField></div>
    <div className="checkout-order-summary" aria-live="polite" aria-atomic="true">
      <h3>{t.checkout.summary.title}</h3>
      <dl>
        <div><dt>{t.checkout.summary.subtotal}</dt><dd><bdi>{formatPrice(subtotal, language)}</bdi></dd></div>
        <div><dt>{t.checkout.summary.shipping}</dt><dd>{shippingFee === null ? t.checkout.summary.selectGovernorate : <bdi>{formatPrice(shippingFee, language)}</bdi>}</dd></div>
        <div className="checkout-order-total"><dt>{t.checkout.summary.total}</dt><dd><bdi>{total === null ? '—' : formatPrice(total, language)}</bdi></dd></div>
      </dl>
      <p>{t.checkout.shippingEstimate}</p>
    </div>
    <button className="btn primary checkout-submit" type="submit" disabled={isSubmitting || Boolean(helpUrl)}>{isSubmitting?t.checkout.sending:t.checkout.submit}</button><p className="checkout-trust-badge"><span aria-hidden="true">🔒</span>{t.checkout.trustBadge}</p><p className={`form-note ${status.type}`.trim()} aria-live="polite" role="status">{statusMessage}</p>{helpUrl && <a className="btn primary checkout-help" href={helpUrl} target="_blank" rel="noopener noreferrer">{t.checkout.statuses.whatsappHelp}</a>}</form></section>;
}
